---
# Docs: https://pre-commit.com/#new-hooks
# Can be tested with:
# pre-commit try-repo ../copier-template-tester copier-template-tester --verbose --all-files

- id: copier-template-tester
  description: 'ctt: copier-template-tester'
  entry: ctt
  language: python
  minimum_pre_commit_version: 2.9.2
  name: copier-template-tester
  pass_filenames: false
